#!/usr/bin/env bash
curl -X PUT "localhost:9200/product"  -H 'Content-Type: application/json' -d'
{
    "settings" : {
        "index" : {
            "number_of_shards" : 3,
            "number_of_replicas" : 0
        }
    },
    "mappings": {
        "_doc": {
            "properties": {
                "pid": {
                   "type": "keyword"
                },
                "product": {
                    "type": "text"
                }
            }
        }
    }
}
'

curl -X PUT "localhost:9200/nori_with_adjv"  -H 'Content-Type: application/json' -d'
{
    "settings" : {
        "index" : {
            "number_of_shards" : 3,
            "number_of_replicas" : 0
        },
        "analysis": {
            "analyzer" :{
                "nori": {
                    "type": "custom",
                    "tokenizer": "nori_tokenizer",
                    "filter": ["pos_filter", "lowercase"]
                }
            },
            "filter": {
                "pos_filter": {
                    "type": "nori_part_of_speech",
                    "stoptags": [
                        "E", "J", "IC", "MAG", "MAJ", "NA", "SC", "SE",
                        "SE", "SH", "SP", "SSC", "SSO", "UNA", "UNKNOWN",
                        "VCP", "VCN", "VSV", "XPN", "XSA",  "XSV"
                    ]
                }
            }
        }
    },
    "mappings": {
        "_doc": {
            "properties": {
                "pid": {
                  "type": "keyword"
                },
                "product": {
                    "type": "text",
                    "term_vector": "with_positions_offsets",
                    "analyzer": "nori"
                }
            }
        }
    }
}
'

# not included : MM, NNB, NNBC, NNG, NNP, NP, NR, SF, SL, SN,
# considerable : "SY", "VA", "VV", "VX", "XR", "XSN"

